name: Build on commit

permissions:
  contents: write

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  build_flink_job:
    name: Build and release Apache Flink Job on commit to dev branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'
          cache: maven
      - name: Build Apache Flink Job with Maven
        run: mvn -f sql-based-streaming-analytics-flink-job/pom.xml --batch-mode --update-snapshots verify
      - name: Prerelease data access UI
        uses: ncipollo/release-action@v1
        with:
          artifacts: "sql-based-streaming-analytics-flink-job/target/sql-based-streaming-analytics-flink-job.jar"
          bodyFile: "CHANGELOG.md"
          prerelease: false
          allowUpdates: true
          replacesArtifacts: true
          tag: "MAIN"
  build_data_access_ui:
    name: Build and release data access UI on commit to dev branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven
      - name: Build data access UI with Maven
        run: mvn -f sql-based-streaming-analytics-data-access-ui/pom.xml --batch-mode --update-snapshots verify
      - name: Prerelease data access UI
        uses: ncipollo/release-action@v1
        with:
          artifacts: "sql-based-streaming-analytics-data-access-ui/target/sql-based-streaming-analytics-data-access-ui.jar"
          bodyFile: "CHANGELOG.md"
          prerelease: false
          allowUpdates: true
          replacesArtifacts: true
          tag: "MAIN"